#define CREATE                           1
#define MERGE                            2
#define SET                              3
#define DELETE                           4
#define REMOVE                           5
#define WITH                             6
#define LBRACE                           7
#define RBRACE                           8
#define UNION                            9
#define MATCH                           10
#define OPTIONAL                        11
#define COMMA                           12
#define LPAREN                          13
#define RPAREN                          14
#define IDENTIFIER                      15
#define COLON                           16
#define DASH                            17
#define LBRACKET                        18
#define RBRACKET                        19
#define ARROW_RIGHT                     20
#define ARROW_LEFT                      21
#define WHERE                           22
#define RETURN                          23
#define DISTINCT                        24
#define AS                              25
#define ORDER                           26
#define BY                              27
#define ASC                             28
#define DESC                            29
#define LIMIT                           30
#define INTEGER                         31
#define SKIP                            32
#define OR                              33
#define AND                             34
#define EQ                              35
#define NE                              36
#define LT                              37
#define LE                              38
#define GT                              39
#define GE                              40
#define PLUS                            41
#define MINUS                           42
#define MULT                            43
#define DIV                             44
#define NOT                             45
#define DOT                             46
#define FLOAT                           47
#define STRING                          48
#define BOOLEAN                         49
#define NULL                            50
