#define UNION                            1
#define MATCH                            2
#define OPTIONAL                         3
#define COMMA                            4
#define LPAREN                           5
#define RPAREN                           6
#define IDENTIFIER                       7
#define COLON                            8
#define DASH                             9
#define LBRACKET                        10
#define RBRACKET                        11
#define ARROW_RIGHT                     12
#define ARROW_LEFT                      13
#define WHERE                           14
#define RETURN                          15
#define DISTINCT                        16
#define AS                              17
#define ORDER                           18
#define BY                              19
#define ASC                             20
#define DESC                            21
#define LIMIT                           22
#define INTEGER                         23
#define SKIP                            24
#define OR                              25
#define AND                             26
#define EQ                              27
#define NE                              28
#define LT                              29
#define LE                              30
#define GT                              31
#define GE                              32
#define PLUS                            33
#define MINUS                           34
#define MULT                            35
#define DIV                             36
#define NOT                             37
#define DOT                             38
#define FLOAT                           39
#define STRING                          40
#define BOOLEAN                         41
#define NULL_TOKEN                      42
